// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe9Ed-V43_C5EncsdVqYF038lf_6ClLZ0',
    appId: '1:731370032746:web:e5df6463bce43fd6830413',
    messagingSenderId: '731370032746',
    projectId: 'health-lens-apps',
    authDomain: 'health-lens-apps.firebaseapp.com',
    storageBucket: 'health-lens-apps.firebasestorage.app',
    measurementId: 'G-BZKZLY9ZP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6PqdC822usiBYt7ngb03w5-5AG5qIbBw',
    appId: '1:731370032746:android:ac932af4b7da2d14830413',
    messagingSenderId: '731370032746',
    projectId: 'health-lens-apps',
    storageBucket: 'health-lens-apps.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe9Ed-V43_C5EncsdVqYF038lf_6ClLZ0',
    appId: '1:731370032746:web:9c3fa2e795ace48a830413',
    messagingSenderId: '731370032746',
    projectId: 'health-lens-apps',
    authDomain: 'health-lens-apps.firebaseapp.com',
    storageBucket: 'health-lens-apps.firebasestorage.app',
    measurementId: 'G-S5ES8F4P55',
  );

}